#!/bin/sh


for i in SECRECY EVCACHE EVNOCACHE IDRSECRACT IDSECR
do
    m4 -D$i JFKr.m4.pi > prot-JFKr-$i.pi
done

for i in SECRECY EVCACHE EVNOCACHE IDISECR
do
    m4 -D$i JFKi.m4.pi > prot-JFKi-$i.pi
done
