#!/bin/sh

ocamlc -o ffgg ffgg.ml

rm -f *.pv 

for i in 10 50 100 150 200
do
    ./ffgg $i > ffgg$i.pv
#    (echo "set traceDisplay = long."; cat ffgg$i.pv) > ffgg$i-long.pv
    (echo "set reconstructTrace = no."; cat ffgg$i.pv; echo "(* EXPECTPV"; echo "RESULT not attacker(M[]) cannot be proved."; echo "END *)") > ffgg$i-notrace.pv
    (echo "(* EXPECTPV"; echo "RESULT not attacker(M[]) is false."; echo "END *)") >> ffgg$i.pv
done

